#!/bin/bash
# REOS Weekly Report Generator
# Purpose: Generate a comprehensive weekly activity report
# Created: 2026-02-09 07:05 JST
# Usage: ./generate_weekly_report.sh [days] (default: 7)

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Parameters
DAYS=${1:-7}
REPORT_FILE="reports/weekly-report-$(date +%Y-%m-%d).md"

echo -e "${BLUE}📊 REOS Weekly Report Generator${NC}"
echo "=================================="
echo "Analyzing last $DAYS days of activity..."
echo ""

# Create reports directory if not exists
mkdir -p reports

# Start report
cat > "$REPORT_FILE" << 'EOF'
# REOS Weekly Activity Report

**Generated**: 
EOF

echo "$(date '+%Y-%m-%d %H:%M JST')" >> "$REPORT_FILE"
cat >> "$REPORT_FILE" << 'EOF'

---

## 📊 Summary Statistics

EOF

# Get commit statistics
TOTAL_COMMITS=$(git log --since="$DAYS days ago" --oneline | wc -l | tr -d ' ')
UNIQUE_AUTHORS=$(git log --since="$DAYS days ago" --format='%an' | sort -u | wc -l | tr -d ' ')
FILES_CHANGED=$(git log --since="$DAYS days ago" --numstat | awk '{files[$3]++} END {print length(files)}')
LINES_ADDED=$(git log --since="$DAYS days ago" --numstat | awk '{sum+=$1} END {print sum}')
LINES_DELETED=$(git log --since="$DAYS days ago" --numstat | awk '{sum+=$2} END {print sum}')

cat >> "$REPORT_FILE" << EOF
- **Period**: Last $DAYS days ($(date -v-${DAYS}d '+%Y-%m-%d') to $(date '+%Y-%m-%d'))
- **Total Commits**: $TOTAL_COMMITS
- **Contributors**: $UNIQUE_AUTHORS
- **Files Modified**: $FILES_CHANGED
- **Lines Added**: +$LINES_ADDED
- **Lines Deleted**: -$LINES_DELETED

---

## 📝 Commit Activity

### All Commits
EOF

# List all commits with one-line summaries
git log --since="$DAYS days ago" --pretty=format:"- %h | %s | %an | %ar" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'


---

## 🎯 Key Activities

### Content Updates
EOF

# Extract content-related commits (docs, fix, feat)
git log --since="$DAYS days ago" --oneline --grep="docs:\|fix:\|feat:" >> "$REPORT_FILE" || echo "- No content updates" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'


### Maintenance & Checks
EOF

# Extract maintenance commits (chore, refactor)
git log --since="$DAYS days ago" --oneline --grep="chore:\|refactor:\|test:" >> "$REPORT_FILE" || echo "- No maintenance activities" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'


### Tools & Automation
EOF

# Extract tool-related commits
git log --since="$DAYS days ago" --oneline --grep="tools:\|ci:\|build:" >> "$REPORT_FILE" || echo "- No tool updates" >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'


---

## 📂 Most Modified Files

EOF

# Top 10 most modified files
git log --since="$DAYS days ago" --name-only --pretty=format: | \
  sort | uniq -c | sort -rn | head -10 | \
  awk '{printf "- **%s** (%d changes)\n", $2, $1}' >> "$REPORT_FILE"

cat >> "$REPORT_FILE" << 'EOF'


---

## 🏥 Current Project Health

EOF

# Run health check and append results
if [ -f "./check_health.sh" ]; then
    ./check_health.sh > /tmp/health_check.txt 2>&1
    HEALTH_STATUS=$(grep -o "EXCELLENT\|GOOD\|FAIR\|POOR" /tmp/health_check.txt | head -1 || echo "UNKNOWN")
    echo "**Status**: $HEALTH_STATUS" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    cat /tmp/health_check.txt >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    rm /tmp/health_check.txt
else
    echo "- Health check script not available" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << 'EOF'


---

## 📈 Project Statistics (Current)

EOF

# Add project stats if available
if [ -f "./project_stats.sh" ]; then
    ./project_stats.sh > /tmp/project_stats.txt 2>&1
    echo '```' >> "$REPORT_FILE"
    cat /tmp/project_stats.txt >> "$REPORT_FILE"
    echo '```' >> "$REPORT_FILE"
    rm /tmp/project_stats.txt
else
    echo "- Project statistics script not available" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << 'EOF'


---

## 🎯 Next Week Focus

Based on TODO.md and recent activity:

EOF

# Extract urgent tasks from TODO.md
if [ -f "TODO.md" ]; then
    echo "### Urgent Tasks" >> "$REPORT_FILE"
    grep -A 5 "### 紧急修复" TODO.md | grep "^- \[ \]" >> "$REPORT_FILE" || echo "- No urgent tasks" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "### Short-term Tasks" >> "$REPORT_FILE"
    grep -A 5 "### 部署与验证\|### 质量改进\|### 自动化改进" TODO.md | grep "^- \[ \]" | head -5 >> "$REPORT_FILE" || echo "- No short-term tasks" >> "$REPORT_FILE"
else
    echo "- TODO.md not found - create task list" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << 'EOF'


---

**Report generated by**: `generate_weekly_report.sh`  
**REOS Principle**: 追溯闭环 - Track project progress through automated reporting
EOF

echo -e "${GREEN}✅ Report generated: $REPORT_FILE${NC}"
echo ""
echo "Summary:"
echo "  - $TOTAL_COMMITS commits in last $DAYS days"
echo "  - $FILES_CHANGED files modified"
echo "  - +$LINES_ADDED/-$LINES_DELETED lines changed"
echo ""
echo -e "${YELLOW}💡 Tip: Review the report and update STATUS.md with key insights${NC}"
